### ISSUE TITLE
Login/Logout functionality

### ISSUE THREAD

**Issue by boy4uck** [BobocodeCourse/gojohnny-project#104]
Anonymous user should see a **Log in button** at the top right corner. This button should redirect the user to the login form. When the user is **logged in**, his/her **name should be displayed** on the screen. (At the right top corner). Then, next to the name, a **Logout button** should be displayed.

* Add header with name and buttons
* Configure logout controller and page (see `SecurityConfigs.java`)

**Comment by hamster4n** [comment]
1. logoutController - this should be a separate controller or a method in the UserRestController?
2. SecurityConfig - a dark forest. How can we get in js the status of the user (logged in or not) and his name?
