### ISSUE TITLE
Implement Place web mvc controller and view

### ISSUE THREAD

**Issue by boy4uck** [BobocodeCourse/gojohnny-project#23]
Create `PlaceController` and put it under **/web/controller**

Implement endpoints:
* `GET /places/add` - returns a Place form **view name** "place_form"
* `POST /places/` - creates a new place basing on input form data

Create a *Thymeleaf* view **place_form.html** and put it under **(webapp/WEB-INF/templates)**:
* add input `name`
* add input `altitude`
* add text area `description`
* configure submit method `post`
* action that points to our `PlaceController` endpoint `../places/`

**Comment by EduardStreltsov** [comment]
done, rebased on fresh master, repushed
