### ISSUE TITLE
Configure database migration with Flyway

### ISSUE THREAD

**Issue by boy4uck** [BobocodeCourse/gojohnny-project#27]
* add flyway **dependency**
* configure **migration scripts location**
* configure **baseline**

**Comment by boy4uck** [comment]
@Dav3on, I will reassign this ticket to somebody else

**Comment by Dav3on** [comment]
@boy4uck sorry, have no clue how to test if it works.

**Comment by Dav3on** [comment]
@boy4uck tried with H2, but even can't connect to schema.

**Comment by boy4uck** [comment]
@Dav3on, okay, we can use your branch. Did you push your last changes?

**Comment by Dav3on** [comment]
@boy4uck yes, that's the latest

**Comment by hamster4n** [comment]
I think that no need to configurate migration script location, because it default. Cant understand how to configurate baseline and how to create bean. I did smth, but my code dont build. So I not create pull request and only push branch. Need help

**Comment by boy4uck** [comment]
Okay, I will check and add my comments here.

**Comment by boy4uck** [comment]
I've added some comments [here](https://github.com/BobocodeCourse/gojohnny-project/commit/5f46886609ee12e6fa8eb2da62a805192479037d)

Basically, when you do a migration first, you need to specify `baseline-on-migrate=true`.
