### ISSUE TITLE
Add profile-based configuration and property files

### ISSUE THREAD

**Issue by boy4uck** [BobocodeCourse/gojohnny-project#28]
### Property files
* put all general properties to **application.properties** file and put it under **resources**
* create **application-test.properties** file and collect all test profile related (H2-related) properties there
* mark all Postgres-related beans as `prod` profile based
* create property file **application-prod.properties**, put all Postgres related properties to this file

### Configurations
* configure *H2* `DataSource` as **test profile** related bean
* load all required properties from property files

**Comment by boy4uck** [comment]
@EduardStreltsov, you own me a beer

**Comment by EduardStreltsov** [comment]
ok)

**Comment by javaRus** [comment]
This task was finished with task "Configure PostgreSQL data source #45" , is it true?

**Comment by boy4uck** [comment]
@javaRus, it contains changes required in feature/45
