### ISSUE TITLE
Create a user login form

### ISSUE THREAD

**Issue by boy4uck** [BobocodeCourse/gojohnny-project#82]
Create a *Thymeleaf* form that will allow users to log in. It should contain:

* email
* password

This form should `POST ` a data to the `/users/login` endpoint

**Comment by boy4uck** [comment]
@EduardStreltsov you should be able to test security. Thus, you can implement a form first. And then try to make it all work. Did you get my idea?

**Comment by EduardStreltsov** [comment]
Kind of
