### ISSUE TITLE
Refactor user registration form to use REST controller

### ISSUE THREAD

**Issue by boy4uck** [BobocodeCourse/gojohnny-project#95]
We are going to build our application using **REST API**. Therefore, for now, we will use MVC controllers only to load HTML pages. 

* refactor `UserController` - remove method that creates user
* refactor  an HTML page - it should now use *JavaScript* that will send user data to the REST contoller
* refactor `UserRestController` and add password encoding

If user is successfully registered, JavaScript should **redirect him to the login page.**

Server should respond with `201 CREATED` if user is created sucessfully. 

*To test `UserRestController` you can use Intellij REST client, and try to save a user.*

**Comment by hamster4n** [comment]
Add to ticket task "encryptUserPassword in UserRestController" please.
